proc import datafile = 'C:/Users/Justin/Desktop/LIMOBAP/LFS2017_cleaned.csv' out = wage replace;
run;
proc reg data = wage plots(maxpoints = none);
model logwage = hhsize elem_grad hs_grad voc_grad col_grad exp married widowed separated annulled rural female visayas mindanao manager professional technician clerical service skilled craft plant_machine armed_forces short_term diff_emp /selection = backward slstay = 0.05 dwprob vif tol collin;
output out = wage p = yhat r = residual rstudent = studresidual cookd = cooksd h = leverage;
run;
proc univariate data = wage normal;
var residual;
run;
proc surveyselect data = wage out = split samprate = 0.5 outall;
run;
data wage;
set split;
if selected = 1 then
group = 1;
else group = 0;
run;
proc anova data = wage; 
class group;
model residual = group;
means group /hovtest=bartlett;
run;
/*data wage2;
set wage;
if abs(studresidual) > 2 or cooksd > 4/sqrt(37149 - 25) or leverage > (2 * 25)/37149 then delete;
run;
proc reg data = wage2 plots(maxpoints = none);
model logwage = hhsize elem_grad hs_grad voc_grad col_grad exp married widowed separated annulled rural female visayas mindanao manager professional technician clerical service skilled craft plant_machine armed_forces short_term diff_emp /selection = backward slstay = 0.05 dwprob vif tol collin;
output out = wage2 p = yhat2 r = residual2 rstudent = studresidual2 cookd = cooksd2 h = leverage2;
run;
proc univariate data = wage2 normal; 
var residual2;
run;
proc surveyselect data = wage2 out = split samprate = 0.5 outall;
run;
data wage2;
set split;
if selected = 1 then
group = 1;
else group = 0;
run;
proc anova data = wage2; 
class group;
model residual2 = group;
means group /hovtest=bartlett;
run;
proc autoreg data = wage2;
model logwage = hhsize hs_grad voc_grad col_grad exp married widowed separated rural female visayas mindanao manager professional technician clerical service craft plant_machine short_term diff_emp /nlag = 2 method = ml dwprob;
output out = wage2 p = yhat3 r = residual3;
run;
proc univariate data = wage2 normal; 
var residual3;
run;
proc anova data = wage2; 
class group;
model residual3 = group;
means group /hovtest=bartlett;
run;*/
proc autoreg data = wage;
model logwage = hhsize elem_grad hs_grad voc_grad col_grad exp married widowed separated annulled rural female visayas mindanao manager professional technician clerical service skilled craft plant_machine armed_forces short_term diff_emp /nlag = 2 method = ml dwprob;
output out = wage p = yhat3 r = residual3;
run;
proc univariate data = wage normal; 
var residual3;
run;
proc anova data = wage; 
class group;
model residual3 = group;
means group /hovtest=bartlett;
run;
